version: "3.8"

services:
  system:
    build:
      dockerfile: system
    image: system:2.0

  springboot:
    container_name: springboot
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - system
    environment:
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:

volumes:
  db-data: